name: Reset Weekly Wants
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Set to true to perform a dry run (no changes will be made)
        required: false
        default: "true"

permissions: {}

jobs:
  reset-weekly-wants:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
      WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Ensure Dry Run
        if: inputs.dry_run == 'true'
        run: |
          echo "DO_WEEKLY_RESET=false" >> $GITHUB_ENV

      - name: Set reset mode
        if: inputs.dry_run != 'true'
        run: |
          echo "DO_WEEKLY_RESET=true" >> $GITHUB_ENV

      - name: Reset Weekly Wants
        run: uv run src/main.py
